runtime: nodejs10

env_variables:
    APP_ACCESS_KEY: process.env.APP_ACCESS_KEY || 'WOmOkR3-Afl_gHWRYSNmD0kS_nUqeaBsRMC3C57oqgM',
    SECRET: process.env.SECRET || 'S1LfoIqHEAkeEqzSLtE7q0v-UrQTHUJBAb1DSwlLYhA',
    CALLBACK_nURL: process.env.CALLBACK_URL || 'http://localhost:3000'